In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [11]:
def tanh(x):
    return np.tanh(x)



def relu(x):
    return np.maximum(0, x)

def elu(x, alpha=1.0):
    # If x is negative, use the ELU formula
    return np.where(x < 0, alpha * (np.exp(x) - 1), x)


In [12]:
# Create three 4x1 arrays
d1 = np.array([[1.2], [0.7], [1.5], [2.3]])
d2 = np.array([[0.3], [0.1], [2.9], [1.4]])
d3 = np.array([[0.9], [0.2], [1.4], [0.9]])

# Concatenate the arrays along the second axis
data = np.concatenate((d1, d2, d3), axis=1)

print(data)

[[1.2 0.3 0.9]
 [0.7 0.1 0.2]
 [1.5 2.9 1.4]
 [2.3 1.4 0.9]]


In [13]:
 def MLP2(data): 
  weights_1_1 = np.array([0.3, 0.3, -0.4, 1.2])
  weights_1_2 = np.array([-0.1, -3.1, 1.4, -2.3])
  weights_1_3 = np.array([1.1, 0.9, 1.3, 0.8])
  weights_2_1 = np.array([0.8, 0.7, 0.3])
  weights_2_2 = np.array([0.5, 0.1, -0.6])
  weights_2_3 = np.array([-0.4, 0.9, 0.7]) 
  weights_3 = np.array([-0.4, 0.8, 1.2]) 

  z1_1 = np.dot(weights_1_1, data)
  z1_2 = np.dot(weights_1_2, data)
  z1_3 = np.dot(weights_1_3, data)

  layer1 = np.array([z1_1, z1_2, z1_3])
  elu_layer1 = elu(layer1)
  print('layer1 : ', elu_layer1)

  z2_1 = np.dot(weights_2_1, elu_layer1)
  z2_2 = np.dot(weights_2_2, elu_layer1)
  z2_3 = np.dot(weights_2_3, elu_layer1)
  
  layer2 = np.array([z2_1, z2_2, z2_3])
  ReLU_layer2 = relu(layer2)
  print('layer2 : ',ReLU_layer2)

  z3 = np.dot(weights_3, ReLU_layer2)
  print('layer3 : ', z3)
  o= tanh(z3)
  
 
  return o

In [14]:
output2 = MLP2(data)

print('Output2 : ', output2)

layer1 :  [[ 2.73        0.64        0.85      ]
 [-0.99583067  0.5        -0.55956835]
 [ 5.74        5.31        3.71      ]]
layer2 :  [[3.20891853 2.455      1.40130216]
 [0.         0.         0.        ]
 [2.0297524  3.911      1.75338849]]
layer3 :  [1.15213546 3.7112     1.54354532]
Output2 :  [0.81846028 0.99880529 0.91271419]
